name: Build and test
on: [push]

permissions:
  id-token: write
  packages: write
  contents: read

jobs:
  java:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven
      run: mvn -B package --file pom.xml

    # Optional: Uploads the full dependency graph to GitHub to improve the quality of Dependabot alerts this repository can receive
    - name: Update dependency graph
      uses: advanced-security/maven-dependency-submission-action@aeab9f885293af501bae8bdfe88c589528ea5e25

  python:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python:
          - "3.12"
    defaults:
      run:
        working-directory: ./python
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python }}
      - name: Install dependencies
        env:
          DEBIAN_FRONTEND: noninteractive
        run: |
          sudo apt-get update -y -qq
          sudo apt-get install -y -qq libicu-dev
          python -m pip install --upgrade pip wheel pyicu
          pip install -e ".[dev]"
      # - name: Run the tests
      #   run: |
      #     make test
      # - name: Partial mypy type-check
      #   run: |
      #     make typecheck
      - name: Build a Python distribution
        run: |
          python3 -m build --wheel
      - name: Publish to PyPI
        if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags')
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          packages-dir: dist/
          skip-existing: true
          verbose: true
